#!@prefix@/bin/sh
[ -f "@prefix@/etc/ssh_host_key" ] || ssh-keygen -t rsa1 -f "@prefix@/etc/ssh_host_key" -N ""
[ -f "@prefix@/etc/ssh_host_dsa_key" ] || ssh-keygen -t dsa -f "@prefix@/etc/ssh_host_dsa_key" -N ""
[ -f "@prefix@/etc/ssh_host_rsa_key" ] || ssh-keygen -t rsa -f "@prefix@/etc/ssh_host_rsa_key" -N ""
