.TH "sslcat" "1" "" "" ucspi-ssl
.SH NAME
.LP
sslcat - prints data from an SSL/TLS connection
.SH SYNOPSIS
.LP
sslcat \fIhost\fR \fIport\fR \fIargs\fR
.SH "DESCRIPTION"
.LP

sslcat connects to \fIhost\fR on \fIport\fR via TCP, and then attempts
an SSL connection.  It prints any data it receives.  sslcat can
be used to transfer binary data.  It does no conversion other than SSL encoding
and decoding.

If \fIport\fR is not supplied, sslcat uses TCP port 443 (HTTPS).

If \fIhost\fR is not supplied, sslcat connects to the local host.

If \fIargs\fR are supplied, they are passed to sslclient unmodified.


.SH AUTHORS
.LP
SuperScript Technology, Inc.

.SH SEE ALSO
sslclient(1),
sslserver(1),
tcpcat(1)

