.TH sslconnect "1" "" "" ucspi-ssl
.SH NAME
.LP
sslconnect - prints data from an SSL/TLS connection
.SH SYNOPSIS
.LP
sslconnect \fIhost\fR \fIport\fR \fIargs\fR
.SH DESCRIPTION
.LP

slconnect connects to \fIhost\fR on \fIport\fR via TCP, and attempts an
SSL connection.  It sends its standard input to the server, printing a CR after
each LF, and prints any data it receives from the server to standard output.
sslconnect can be used to fetch binary data.  It does no conversion
other than SSL encoding and decoding on received data.

If \fIport\fR is not supplied, sslconnect uses TCP port 443 (HTTPS).

If \fIhost\fR is not supplied, sslconnect connects to the local host.

If \fIargs\fR are supplied, they are passed to sslclient unmodified.

.SH AUTHORS
.LP
SuperScript Technology, Inc.

.SH SEE ALSO
sslclient(1),
sslserver(1),
tcpcat(1)

