.TH "MOUNT.WIKIPEDIAFS" "8" 
.SH "NAME" 
mount.wikipediafs \(em A program to mount WikipediaFS, a filesystem that allows to view 
and edit Wikipedia articles as if they were real files. 
.SH "SYNOPSIS" 
.PP 
\fBmount.wikipediafs \fR\fImountpoint\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents the \fBmount.wikipediafs\fR         command and general usage of WikipediaFS. 
.PP 
WikipediaFS allows to view and edit Wikipedia articles as if 
they were real files. \fBmount.wikipediafs\fR mounts a WikipediaFS 
filesystem. 
 
.PP 
To connect through an HTTP proxy, it possible to use 
the $http_proxy environment variable. 
.SH "CONFIGURATION" 
.PP 
The first time WikipediaFS is run, an XML configuration file is 
generated in ~/.wikipediafs/config.xml. It is possible to edit it 
later to add more Wikipedia or Mediawiki-based sites. Each site 
entry can define the following elements. Elements marked with an * are 
mandatory. 
.IP "dirname*" 10 
Is the name of the directory through which you will access 
to the site. 
 
.IP "host*" 10 
Is the host of the site. 
 
.IP "basename*" 10 
Is the base of urls used by the site. Most of the time, it 
will be /dir/where/mediawiki/is/installed/index.php. For 
Wikipedia, it will be /w/index.php. 
 
.IP "username and password" 10 
Enables to edit articles with one's 
login. 
 
.IP "httpauth_username and httpauth_password" 10 
Can be used for Mediawiki sites protected 
with HTTP authentication (Apache's .htaccess). 
 
.IP "https" 10 
Use HTTPS instead of HTTP. 
 
.SH "MOUNT" 
.PP 
\fBmount.wikipediafs\fR mountpoint/ 
.PP 
To run mount.wikipediafs without root privileges, you may have to set 
the right permissions for /usr/bin/fusermount and /dev/fuse if your 
distribution has not already done it for you. For example, 
.PP 
# adduser your_username fuse 
.PP 
# chmod 4750 /usr/bin/fusermount 
.PP 
# chgrp fuse /dev/fuse /usr/bin/fusermount 
.PP 
(You may have to log out and log in again so that changes are taken 
into account.) 
.SH "UNMOUNT" 
.PP 
\fBfusermount\fR \-u mountpoint/ 
.PP 
or simply 
.PP 
\fBumount\fR mountpoint/ 
.SH "FSTAB" 
.PP 
Alternatively, you can mount WikipediaFS through fstab. 
.PP 
To do so, add this line to /etc/fstab: 
.PP 
none /mnt/wfs/ wikipediafs noauto,nouser 
.PP 
Replace noauto by auto if you want WikipediaFS to be mounted at 
boot.  
.PP 
Replace nouser by user if you want to allow simple users to use 
WikipediaFS. 
.PP 
A symbolic link from /usr/bin/mount.wikipediafs to 
/sbin/mount.wikipediafs is needed if WikipediaFS is mounted through 
fstab. 
.PP 
Then, traditional mount and unmount commands can be used with 
WikipediaFS. 
.SH "SAMPLE USAGE" 
.PP 
This section demonstrates possible usage of WikipediaFS via the command 
line, though it is also possible to use WikipediaFS with a graphical file 
explorer. 
.PP 
$ mount /mnt/wfs/ 
 
WikipediaFS is now mounted in /mnt/wfs/ 
.PP 
$ cd /mnt/wfs/ 
 
We are now at the WikipediaFS root. 
.PP 
$ ls 
 
mblondel.org/ 
 
This directory has been defined in the configuration file. 
.PP 
$ mkdir wikipedia-en/ 
 
WikipediaFS recognizes the "site-lang" pattern for the sites from the Wikimedia 
Foundation. 
.PP 
$ ls 
 
mblondel.org/  wikipedia-en/ 
.PP 
$ ls wikipedia-en/ 
 
Nothing is listed because we have not used any file yet. 
.PP 
$ cat wikipedia-en/Japan.mw | less 
 
The Japan article is fetched on en.wikipedia.org and displayed. Note that 
the .mw extension is required. 
.PP 
$ ls wikipedia-en/ 
 
Japan.mw 
 
Japan.mw is now listed because it has been accessed once. 
.PP 
$ vi mblondel.org/Test.mw 
 
An article can be edited with a text editor. Looking at the article with a web 
browser, the changes have been performed correctly. 
 
To give a summary to your changes, use [[Summary: a sentence summary]] in the 
body of the article. It will be removed before the article is saved. 
.PP 
$ cp wikipedia-en/Japan.mw ~/Desktop/ 
 
This backups the online article to the local disk. 
.PP 
$ cp wikipedia-en/Japan.mw mblondel.org/ 
 
This copies the wikipedia-en article to the mblondel.org entry. 
.PP 
$ rm mblondel.org/Test.mw 
 
This only removes the article from the directory, not from the site, 
hopefully. 
.PP 
$ mkdir \-p mblondel.org/Foo/Bar/ 
.PP 
$ vi mblondel.org/Foo/Bar/Code.mw 
 
Subpages are supported. You need to create the directories first. 
.SH "AUTHOR" 
.PP 
This manual page was written by Mathieu Blondel .  
.PP 
This manual page is (c) 2006-2007 of Mathieu Blondel  and licensed under the terms of the GPLv2 or higher 
.SH "SEE ALSO" 
.PP 
\fBmount\fP\fB(8)\fP, 
\fBfstab\fP\fB(5)\fP      
.\" created by instant / docbook-to-man, Fri 30 Nov 2007, 18:50 
